config/routes.rb
Rails.application.routes.draw do
  get 'home/welcome'

  get 'shows/index'

  get 'shows/show'

  get 'chefs/index'

  get 'chefs/show'

  get 'recipes/category_index'

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#welcome'

  concern :recipeable do
    resources :recipes
  end

  concern :videoable do
    resources :videos
  end

  concern :showable do
    resources :shows
  end
  
  resources :recipes
  resources :cuisines, concerns: [:recipeable, :videoable]
  resources :courses, concerns: [:recipeable, :videoable]
  resources :shows, concerns: [:recipeable, :videoable]
  resources :chefs, concerns: [:recipeable, :videoable, :showable]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :shows
  has_many :recipes
  has_many :videos

  has_one :picture, as: :imageable
  accepts_nested_attributes_for :picture
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :recipes
  has_many :videos
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :recipes
  has_many :videos
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true

  mount_uploader :image, ImageUploader

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :cuisine
  belongs_to :course
  belongs_to :chef
  belongs_to :show

  has_one :picture, as: :imageable
  accepts_nested_attributes_for :picture

  def self.find_all_recipes(recipeable, search)
    if search.present?
      search(search)
    else
      recipeable.present? ? recipeable.recipes.includes(:picture) : Recipe.includes(:picture).all
    end
  end
 
  def self.find_recipes(category)
    if category.eql?("cuisine")
      recipes = Recipe.includes(:picture, :cuisine).order('name ASC')
    elsif category.eql?("course")
      recipes = Recipe.includes(:picture, :course).order('name ASC')
    elsif category.eql?("show")
      recipes = Recipe.includes(:picture, :show).order('name ASC')
    end
  end
 
  def self.group_recipe(category, recipes)
    if category.eql?("cuisine")
      return recipes.group_by(&:cuisine)
    recipes = Recipe.includes(:picture, :cuisine).order('name ASC')
    elsif category.eql?("course")
      return recipes.group_by(&:course)
    elsif category.eql?("show")
      return recipes.group_by(&:show)
    end
  end

  def self.search(search)
    Recipe.includes(:picture).where('LOWER(name) LIKE ?', "%#{search.downcase}%")
  end
end
 

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :chef
  has_many :recipes
  has_many :videos

  has_one :picture, as: :imageable
  accepts_nested_attributes_for :picture
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if !user.email?
      end
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :cuisine
  belongs_to :course
  belongs_to :show
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

#  before_action :authenticate_user!
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  def index
    @chefs = Chef.includes(:picture).all
  end

  def show
  end

  private

  def chef_params
    params.require(:chef).permit(:name, picture_attributes: [:name, :image])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  respond_to :json, :html
  
  before_action :find_recipeable, only: [:index, :show]

  def index
    @recipes = Recipe.find_all_recipes(@recipeable, params[:search])
    if @recipeable.present?
      respond_with(@recipeable, @recipes)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    respond_with(@recipeable, @recipe)
  end

  def new
  end

  def category_index
    @category = params[:category]
    recipes = Recipe.find_recipes(@category)
    @grouped_recipes = Recipe.group_recipe(@category, recipes)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :preparation_method,\
	 :preparation_time, :cooking_time)
  end

  def find_recipeable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return @recipeable = $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.includes(:picture).all
  end

  def show
  end

  private

  def show_params
    params.require(:show).permit(:name, picture_attributes: [:name, :image])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/chefs/index.html.erb
<h1>Chefs</h1>
<% @chefs.each do |chef|%>
  <% if chef.picture.present? %>
    <%= image_tag chef.picture.image_url(:thumb)  %>
  <%end%>
  <%= chef.name%>
  <br/>
  <br/>
<%end%>

app/views/chefs/show.html.erb
<h1>Chefs#show</h1>
<p>Find me in app/views/chefs/show.html.erb</p>

app/views/home/welcome.html.erb
<h1>Home Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food Food</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if user_signed_in? %>
    <div class="session_links">
      <%= link_to 'Logout', destroy_user_session_path, id: "sign_out", method: :delete %>
    </div>
  <% else %>
    <div class="session_links">
    <%= link_to 'Login', new_user_session_path %>
    <%= link_to 'Login with Facebook', user_omniauth_authorize_path(:facebook), id: "sign_in" %>
    </div>
  <% end %>
  <br/>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#food-food-navbar-collapse-1">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Food Food", root_url, html_options = {:class => "navbar-brand"} %>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="food-food-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home<span class="sr-only">(current)</span></a></li>
        <li text-decoration="none"><%= link_to "Chefs", chefs_path %></li>
        <li><%= link_to "Shows", shows_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Recipes<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Cuisine", recipes_category_index_path(category: "cuisine") %></li>
            <li><%= link_to "Course", recipes_category_index_path(category: "course") %></li>
            <li class="divider"></li>
            <li><%= link_to "By Show", recipes_category_index_path(category: "show") %></li>
          </ul>
        </li> <!-- recipes dropdown-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Videos<span class="caret"></span></a>
 	  <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Cuisine","#" %></li>
            <li><%= link_to "Course", "#" %></li>
            <li class="divider"></li>
            <li><%= link_to "By Show", "#" %></r kali>
          </ul>
        </li> <!-- videos dropdown -->
        <%= form_tag recipes_path, method: 'get', html: { :class => "navbar-form navbar-left" } do%> 
	  <p>
 	    <%= text_field_tag :search, params[:search], placeholder: "Search Recipes"%>
	    <%= submit_tag "Search" %>
          </p>
	<%end%>
        <% if user_signed_in? %>
          <li class="pull-right"><%= link_to "Submit Recipe", "#" %></li>
        <%end%>
      </ul>
    </div>
  </nav>
</head>
<body>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/recipes/category_index.html.erb
<h1>Recipe by <%= @category %></h1>
<% @grouped_recipes.each do |category, recipes| %>
  <hr>
  <%if category.present? %>
    <b><%= link_to category.name, polymorphic_url([category, :recipes], category: category) %></b>
  <%end%>
  <br/><br/>
  <% recipes.each do |recipe| %>
    <% unless recipe.picture.blank? %>
      <%= link_to(image_tag(recipe.picture.image_url(:thumb)), recipe_path(recipe)) %> 
    <%end%>
    <br/>
    <%= recipe.name%>
    <br/><br/>
  <%end%>
<%end%>

app/views/recipes/index.html.erb
<h1>Recipe Index Page</h1>
<p>
<% @recipes.each do |recipe|%>
  <%= link_to(image_tag(recipe.picture.image_url(:thumb)), polymorphic_url([@recipeable, recipe])) %>
  <br/>
  <%= recipe.name %>
  <br/>
<% end %>
</p>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

app/views/recipes/show.html.erb
<h1>Recipe</h1>
  <p>
  <%= image_tag @recipe.picture.image_url(:thumb) %>
  <br/>
  <%= @recipe.name %>
<p>
<br/>
<p>
  <h3>Ingredients</h3>
  <hr>
  <%= @recipe.ingredients %>
</p>
<p>
  <h3>Preparation Method</h3>
  <hr>
  <%= @recipe.preparation_method %>
</p>
<p>
  <% if @recipe.chef.picture.present? %>
    <%= image_tag @recipe.chef.picture.image_url(:thumb) %>
  <%end%>
  <%= @recipe.chef.name %>
</p>

<p> 
  <h3>Preparation Time(minutes)</h3>
  <%= @recipe.preparation_time %>
  <h3>Cooking Time(minutes)</h3>
  <%= @recipe.cooking_time %>
</p>

app/views/shows/index.html.erb
<h1>Shows</h1>
<% @shows.each do |show| %>
  <% unless show.picture.blank? %>
    <%= image_tag show.picture.image_url(:thumb)%>
  <%end%>
  <%= show.name%>
  <br/><br/>
<%end%>

app/views/shows/show.html.erb
<h1>Shows#show</h1>
<p>Find me in app/views/shows/show.html.erb</p>